#!/bin/bash
set -e


[ -e ../template/zfunctions.sh ] && source ../template/zfunctions.sh

source_version_info
debian_changelog
cleanup_old_builds
debian_cleanup
debian_foo_basics
basic_control nox
debian_rules

# debian

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/copyright \
    > ./debian/copyright

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-nox-livesettings.lintian-overrides \
    > ./debian/${CODENAME_SAFE}-nox-livesettings.lintian-overrides
sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-nox-livesettings.preinst \
    > ./debian/${CODENAME_SAFE}-nox-livesettings.preinst

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-nox-livesettings.install \
    > ./debian/${CODENAME_SAFE}-nox-livesettings.install

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-nox-livesettings.service \
    > ./debian/${CODENAME_SAFE}-nox-livesettings.service

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-nox-settings.install \
    > ./debian/${CODENAME_SAFE}-nox-settings.install

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-nox-settings.postinst \
    > ./debian/${CODENAME_SAFE}-nox-settings.postinst


## template

cp -a ../template/etc .


sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/nox-cheatcodes \
    > ./nox-cheatcodes
chmod 755 ./nox-cheatcodes

grub_template nox


exit 0
