#!/bin/bash
set -e


source ./functions.sh

source_version_info
debian_changelog
cleanup_old_builds
debian_cleanup
debian_foo_basics
basic_control nox
debian_rules

# debian

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@FLAVOUR\@/${FLAVOUR}/g" \
    ./debtemplate/copyright \
    > ./debian/copyright
chmod 755 ./debian/get-template

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/get-template \
    > ./debian/get-template
chmod 755 ./debian/get-template

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/lintian-overrides \
    > ./debian/${CODENAME_SAFE}-nox-livesettings.lintian-overrides
sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/livesettings.preinst \
    > ./debian/${CODENAME_SAFE}-nox-livesettings.preinst
sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/livesettings.install \
    > ./debian/${CODENAME_SAFE}-nox-livesettings.install
sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/livesettings.service \
    > ./debian/${CODENAME_SAFE}-nox-livesettings.service

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/settings.install \
    > ./debian/${CODENAME_SAFE}-nox-settings.install
sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/settings.postinst \
    > ./debian/${CODENAME_SAFE}-nox-settings.postinst

## template

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./template/nox-cheatcodes \
    > ./nox-cheatcodes
chmod 755 ./nox-cheatcodes

grub_template nox


exit 0
