#!/bin/bash

WALLPAPER=paintitblack
CODENAME_SAFE=paintitblack
DESCRIPTION=PaintItBlack
VERSION=2016.1.0
DISTRIBUTION=next

# Gdm3 and Gnome settings
BACKGROUND_RENDERING_OPTION="stretched"


# FLL_LIVE_USER for 10-live-cd.pkla
FLL_LIVE_USER=siducer
