#!/bin/bash

cd /etc/skel
for i in $(find . -type d); do
    [ ! -d ~/$i ] &&  mkdir -p ~/$i
    for k in $(find $i -maxdepth 1 -type f); do
        [ -e ~/${k#./} ] && [ ! "x$(cmp $k ~/${k#./})" = "x" ]  && cp -v $k ~/${k#./}.sidnew
        [ ! -e ~/${k#./} ] && cp -v $k ~/${k#./}
    done
done
