#!/bin/sh


PATH=/sbin:/usr/sbin:/bin:/usr/bin
NAME="common-cheatcodes"

###
# source distro-defaults
###

if [ -r /etc/default/distro ]; then
	. /etc/default/distro
fi

###
# source lsb functions
###
. /lib/lsb/init-functions

###
# source fll functions
###
. /lib/init/fll

###
# read in variables from /etc/default/fll-locales
###
if [ -r /etc/default/fll-locales ]; then
	. /etc/default/fll-locales
fi

FLL_LIVE_USER_HOME=$(getent passwd ${FLL_LIVE_USER} | cut -d \: -f 6)

###
# cheatcode handling
###

for param in $(cat /proc/cmdline); do
	case "${param}" in
		flldebug=*)
			if [ "${param#flldebug=}" = "${NAME}" ] || [ "${param#flldebug=}" = "all" ]; then
				fll_redirect
			fi
			;;
		nointro)
			NOINTRO="nointro"
			;;
	esac
done

no_intro()
{
for mntpnt in /fll/*; do
	if [ -d "${mntpnt}" ] && [ -f "${mntpnt}/index.html" ]; then
		INDEXFILE="${mntpnt}/index.html"
		for ext in svg png gif ico; do
			if [ -f "${mntpnt}/${FLL_CDROM_INDEX_ICON}.${ext}" ]; then
				INDEXICON="${mntpnt}/${FLL_CDROM_INDEX_ICON}.${ext}"
				break
			fi
		done
		break
	fi
done


###
# create desktop shortcut to index.html
###
if [ -f "${INDEXFILE}" ] && [ ! -f "${FLL_LIVE_USER_HOME}/Desktop/${FLL_DISTRO_NAME}.desktop" ]; then
    [ ! -d ${FLL_LIVE_USER_HOME}/Desktop ] && sudo -u ${FLL_LIVE_USER} mkdir ${FLL_LIVE_USER_HOME}/Desktop
    cat > "${FLL_LIVE_USER_HOME}/Desktop/${FLL_DISTRO_NAME}.desktop" <<EOF
#!/usr/bin/env xdg-open
[Desktop Entry]
Encoding=UTF-8
Type=Application
Exec=x-www-browser file:${INDEXFILE}
Icon=${INDEXICON}
Terminal=0

Name=${FLL_CDROM_INDEX}
GenericName=${FLL_CDROM_INDEX}
EOF
    chmod 755 "${FLL_LIVE_USER_HOME}/Desktop/${FLL_DISTRO_NAME}.desktop"
    chown ${FLL_LIVE_USER} "${FLL_LIVE_USER_HOME}/Desktop/${FLL_DISTRO_NAME}.desktop"
    chgrp ${FLL_LIVE_USER} "${FLL_LIVE_USER_HOME}/Desktop/${FLL_DISTRO_NAME}.desktop"
echo "Release Notes scheduled for start." 
fi
}

do_start()
{
if [ -z "${NOINTRO}" ]; then
	no_intro
fi
}

case "${1}" in
    start)
        log_daemon_msg "${NAME}"
        do_start
        log_end_msg "${?}"
        ;;
    stop)
        ;;
    restart|force-reload)
        echo "Error: argument '${1}' not supported" >&2
        exit 3
        ;;
    *)
        echo "Usage: ${NAME} {start|stop}" >&2
        exit 3
        ;;
esac
