#!/bin/sh
# postinst script #PACKAGE#

set -e


add_loop_module() {
    if  [ ! -f /etc/modules-load.d/loop.conf ]; then
        mkdir -p /etc/modules-load.d
        echo loop > /etc/modules-load.d/loop.conf
    fi
}


case "$1" in
    configure)
        add_loop_module
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
