#!/bin/sh
# postinst script for #PACKAGE#

set -e

set_sddm_session() {
        sed -e "s/User=/User=siducer/g" \
            -e "s/Session=/Session=mate.desktop/g" \
            /etc/sddm-*.conf \
            > /etc/sddm.conf
}


case "$1" in
    configure)
        set_sddm_session
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
