#!/bin/sh
# postinst script for #PACKAGE#

set -e

if [ -f /etc/default/distro ]; then
    . /etc/default/distro
fi


case "$1" in
    configure)
        cp -af /usr/share/cblues-nox-settings/etc/*  /etc
        ## enable iwd.service ##
        systemctl enable --now iwd.service
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
