# Auto-generated by canto because you don't have one.
# Please copy to/create ~/.canto/conf.py

#add("http://rss.slashdot.org/slashdot/Slashdot")
#add("http://reddit.com/.rss")
#add("http://kerneltrap.org/node/feed")
#add("http://codezen.org/canto/feeds/latest")

add("https://siduction.org/feed/", tags=["siduction.org"])
add("https://www.linux-magazin.de/feed/", tags=["Linux-Magazin Online News"])
add("https://www.kernel.org/feeds/kdist.xml", tags=["Latest Linux Kernel Versions"])
add("https://distrowatch.com/news/dw.xml", tags=["DistroWatch.com: News"])
add("https://distrowatch.com/news/dwp.xml", tags=["DistroWatch.com: Packages"])
add("https://distrowatch.com/news/dwd.xml", tags=["DistroWatch.com: Distributions"])
add("https://www.heise.de/rss/heise.rdf", tags=["Heise Online"])
