# Auto-generated by canto because you don't have one.
# Please copy to/create ~/.canto/conf.py

#add("http://rss.slashdot.org/slashdot/Slashdot")
#add("http://reddit.com/.rss")
#add("http://kerneltrap.org/node/feed")
#add("http://codezen.org/canto/feeds/latest")

add("http://news.siduction.org/feed/", tags=["news.siduction.org"])
add("http://siduction.de/index.php?module=news&func=view&theme=rss", tags=["siduction.org"])
add("http://www.linux-magazin.de/rss/feed/news", tags=["Linux-Magazin Online News"])
add("http://kernel.org/kdist/rss.xml", tags=["Latest Linux Kernel Versions"])
add("http://distrowatch.com/news/dw.xml", tags=["DistroWatch.com: News"])
add("http://distrowatch.com/news/dwp.xml", tags=["DistroWatch.com: Packages"])
add("http://distrowatch.com/news/dwd.xml", tags=["DistroWatch.com: Distributions"])
add("http://www.freiesmagazin.de/rss.xml", tags=["freiesMagazin"])
add("http://www.pro-linux.de/rss/1/3/rss20_alles.xml", tags=["Pro-Linux"])
add("http://www.heise.de/newsticker/heise.rdf", tags=["Heise Online"])
